
trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
 terraform_version: 1.0.0
 workspace: hubeastus2

steps:
- script: |
      wget --quiet https://releases.hashicorp.com/terraform/$(terraform_version)/terraform_$(terraform_version)_linux_amd64.zip
      unzip terraform_$(terraform_version)_linux_amd64.zip
      rm terraform_$(terraform_version)_linux_amd64.zip
      chmod +x terraform
  displayName: Install Terraform

- task: AzureCLI@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN (270086d6-d0b4-4c74-87dc-44ad8c9b6fed)'
    addSpnToEnvironment: true
    scriptLocation: inlineScript
    failOnStandardError: false
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query="id" -o tsv)"
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]${servicePrincipalId}"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]${servicePrincipalKey}"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(az account show --query="tenantId" -o tsv)"
      echo "##vso[task.setvariable variable=ARM_ACCESS_KEY]$(az storage account keys list -n oclabstor --query=value -o tsv)"
  displayName: 'Setup Authentication'  

# Run Terraform Init
- script: |
    cd  '$(Build.Repository.LocalPath)/prsys/hub/terraform'
         $(Build.Repository.LocalPath)/terraform init -no-color -input=false

# Select Terraform Workspace
- script: |
    cd  '$(Build.Repository.LocalPath)/prsys/hub/terraform'
        $(Build.Repository.LocalPath)/terraform init -no-color -input=false 
        $(Build.Repository.LocalPath)/terraform workspace new $(workspace)
        $(Build.Repository.LocalPath)/terraform workspace select $(workspace)
  displayName: 'Terraform Workspace Select'


# Run Terraform Delete
- script: |
    $(Build.Repository.LocalPath)/terraform destroy -no-color -input=false -auto-approve 
  displayName: 'Terraform Delete'
  workingDirectory: $(Build.Repository.LocalPath)/prsys/hub/terraform
  enabled: true
